### ISSUE TITLE
Chrome 72: Extension non-functional

### ISSUE THREAD

**Issue by moderndeveloperllc** [RESTEDClient/RESTED#154] opened 2019-01-30 20:55 UTC
@esphen It looks like Chrome 72 has broken things a bit:
```
Uncaught (in promise) TypeError: Illegal invocation: Function must be called on an object of type StorageArea
    at rested.js:29
    at new Promise (<anonymous>)
    at new t (rested.js:6)
    at i (rested.js:29)
    at e.<anonymous> (rested.js:29)
    at o (rested.js:29)
    at Generator._invoke (rested.js:29)
    at Generator.e.(anonymous function) [as next] (chrome-extension://eelcnbccaccipfolokglfhhmapdchbfg/dist/rested.js:29:19339)
    at r (rested.js:29)
    at rested.js:29
```

Based on [this bug fix](https://github.com/wtetsu/mouse-dictionary/issues/16) on a different repo, it looks like an issue with Promises and handling the async calls. [Another extension](https://github.com/KeithHenry/chromeExtensionAsync/issues/10) had this issue too.

**Comment by esphen** [comment] 2019-01-30 21:13
Interesting. I wasn't aware. Thanks for the heads up.

The linked issues are a great place to start looking. I probably won't have time to dig in until next week, but feel free to have a look in the mean time if you want to help out ✌️

**Comment by PeteDaGuru** [comment] 2019-02-01 13:11
Yeah, this hit me on my latest upgrade -.v 72.0.3626.81 .  Thankfully, it still works on Firefox!
 Oh, and thank you for such a  nice lightweight client!

**Comment by filipesperandio** [comment] 2019-02-01 13:30
Came across this while search for this error on my extension.
Turns out an quick fix is to bind the functions back to its holding object like:
`chrome.storage.sync.get.bind(chrome.storage.sync)`

**Comment by KeithHenry** [comment] 2019-02-05 08:51
Now fixed in https://www.npmjs.com/package/chrome-extension-async version 3.3.1, apologies for the delay.

**Comment by esphen** [comment] 2019-02-08 07:44
I'm having issues reproducing this issue. Despite my best efforts in Chrome, it seems to work just fine. Very strange. I don't see why my Chrome 72.0.3626.81 should be different to yours.

Are you able to reproduce the issue with a clean chrome profile? Any steps to reproduce from there?

**Comment by garry-kevin** [comment] 2019-02-08 09:08
> I'm having issues reproducing this issue. Despite my best efforts in Chrome, it seems to work just fine. Very strange. I don't see why my Chrome 72.0.3626.81 should be different to yours.
> 
> Are you able to reproduce the issue with a clean chrome profile? Any steps to reproduce from there?
Using Chrome 72.0.3626.81. Showing this error now.
[Screenshot](https://ibb.co/CBg60rk)

**Comment by zuxianghuang** [comment] 2019-03-20 07:42
chrome Version 73.0.3683.75 (Official Build) (64-bit)
have the same problem
![image](https://user-images.githubusercontent.com/7301534/54667202-bc35e580-4b26-11e9-821b-5e1f7f6e7731.png)

**Comment by avonwyss** [comment] 2019-04-30 12:38
Getting the same problem with Chrome 74.0.3729.108

**Comment by csimi** [comment] 2019-06-14 13:30
@esphen please check the pr referencing this issue above as the bug for this is from that repo

**Comment by Jotune** [comment] 2019-07-12 13:04
Same problem with Opera 62.0.3331.72

**Closed** 2019-07-23 19:03 UTC

**Comment by esphen** [comment] 2019-07-23 19:12
The PR @csimi was referring to was merged today and 2.3.1 was just released, should be rolling out soon. Hope that fixes the issue.

The opera developer portal seems to be down at this time, so I have not been able to upload there yet unfortunately. Will keep trying.

**Comment by esphen** [comment] 2019-07-23 19:40
Submitted for Opera as well now

**Comment by csimi** [comment] 2019-07-23 19:43
I can confirm that it works in Chrome again.
Thanks.
